Feature/setup
Dandush03/JS-Library pull request #1
Opened 2020-04-09 20:02 UTC by Dandush03

# Created Library Project
###### Microverse First JS Project

### In this project I used:
- HTML5
- CSS3
- JS
- ES6
- VSCode

2020-04-11 16:28 UTC, shloch requested changes
## hello @Dandush03 ,

Great job.........looks perfect and professional

### one more thing to do below before a last thumbs up....happy coding

2020-04-11 16:28 UTC, shloch commented on script.js
> +  myLibrary.push(book);
Apply minimum security of checking whether user has filled form before submission........
Else we get something like the screenshot below

![Screen Shot 2020-04-11 at 5 28 04 PM](https://user-images.githubusercontent.com/40712459/79049150-9e4b8f00-7c19-11ea-8daf-783c2ea2adf2.png)

2020-04-12 02:14 UTC, Dandush03 commented
#  Thanks for your Code Review :exclamation: :exclamation: 
#### I implement a validation rule for the form

## Happy Coding :computer: 
## Best Regards :exclamation: :exclamation: 
### Daniel Laloush

2020-04-12 12:18 UTC, shloch requested changes
GREAT JOB
![Screen Shot 2020-04-12 at 1 13 00 PM](https://user-images.githubusercontent.com/40712459/79068472-056f4f00-7cbf-11ea-9ddd-49b27e279821.png)
![Screen Shot 2020-04-12 at 1 13 26 PM](https://user-images.githubusercontent.com/40712459/79068487-29329500-7cbf-11ea-99d8-84b3ed106d26.png)

![Screen Shot 2020-04-12 at 1 13 38 PM](https://user-images.githubusercontent.com/40712459/79068491-39e30b00-7cbf-11ea-8738-c20a895d3ed7.png)

![Screen Shot 2020-04-12 at 1 13 51 PM](https://user-images.githubusercontent.com/40712459/79068492-3d769200-7cbf-11ea-99eb-722ce7375a5c.png)


## put the linting config back for final thumbs up  😃😃😃😃😃😃

2020-04-12 12:18 UTC, shloch commented on .eslintrc.json
> +}
You shouldn't have touched this config though, please change and use the config file provided by microverse and re-run for linting errors  
[ [see config here](https://github.com/microverseinc/linters-config/blob/master/javascript/.eslintrc.json) ]

2020-04-12 12:18 UTC, shloch commented on .eslintrc.json
> +}
![Screen Shot 2020-04-12 at 1 19 39 PM](https://user-images.githubusercontent.com/40712459/79068551-b249cc00-7cbf-11ea-99de-11a7caef5389.png)

2020-04-12 23:21 UTC, Dandush03 commented
# Hey :wave: :exclamation: 
## Sadly this setting are set up for 2018 and I thought i would be a good idea to update it. but there you go I left it as posted in here.
#### Thanks for your time

2020-04-13 09:34 UTC, shloch approved these changes
### we're good to go bro.......on to the next project
## happy coding 👏 👏 👏 👏 👏 

![accomplished](https://user-images.githubusercontent.com/40712459/79110438-4ffdd380-7d72-11ea-82f0-f4608b35317d.jpg)

2020-04-13 13:11 UTC, closed without merging